version: '3'
services:
  logstash:
    build: ./logstash
    container_name: logstash
    networks:
      - elastic
    volumes:
      - lsdata:/usr/share/logstash/data
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m

networks:
  elastic:
    driver: bridge

